pipeline {
    agent any
    
    stages {
        stage('fetchCode') {
            steps {
                git branch: 'main', credentialsId: 'git_cred', url: 'https://github.com/Hari0147/TechEmployees.git'
            }
        }
        
        stage('build frontend') {
            steps {
                dir('frontend') {
                    sh '''
                        python3 -m venv venv
                        ./venv/bin/python -m pip install --upgrade pip
                        ./venv/bin/python -m pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('BuildDockerImage') {
            steps {
                dir('frontend') {
                    sh '''
                        docker build -t hari00147/tech-employee/frontend-service:latest .
                    '''
                }
            }
        }
    }
}
