pipeline {
    agent any
    
    stages {
        stage('fetchCode') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [sparseCheckout([[path: 'auth-service']])], userRemoteConfigs: [[credentialsId: 'git_cred', url: 'https://github.com/Hari0147/TechEmployees.git']])
            }
        }
        
        stage('BuildDockerImage') {
            steps {
                dir('auth-service') {
                    sh '''
                        docker build -t hari00147/tech-employees:auth-service .
                    '''
                }
            }
        }
        stage('pushimage') {
            steps {
                withCredentials([string(credentialsId: 'Docker_pass', variable: 'Docker_pass')]) {
                  sh '''
                  echo "$Docker_pass" | docker login -u hari00147 --password-stdin
                  docker push hari00147/tech-employees:auth-service
                  '''
                }
            }
        }
    }
}
