pipeline {
    agent any
    
    stages {
        stage('fetchCode') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [sparseCheckout([[path: 'department-service']])], userRemoteConfigs: [[credentialsId: 'git_cred', url: 'https://github.com/Hari0147/TechEmployees.git']])
            }
        }
        
        stage('BuildDockerImage') {
            steps {
                dir('department-service') {
                    sh '''
                        docker build -t hari00147/tech-employee/department-service:latest .
                    '''
                }
            }
        }
    }
}
